# Generated by Django 4.0.4 on 2022-05-21 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authuser',
            name='user_type',
            field=models.PositiveSmallIntegerField(choices=[(4, 'Reviewer'), (2, 'Customer'), (1, 'Product Manager'), (3, 'Customer Manager')], null=True),
        ),
    ]
