# Generated by Django 4.0.4 on 2022-05-21 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_alter_authuser_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authuser',
            name='user_type',
            field=models.PositiveSmallIntegerField(choices=[(4, 'Reviewer'), (1, 'Product Manager'), (2, 'Customer'), (3, 'Customer Manager')], null=True),
        ),
        migrations.AlterField(
            model_name='reviewer',
            name='contact',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='reviewer',
            name='name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='reviewer',
            name='profilepicture',
            field=models.ImageField(blank=True, default='/assets/default_pfp.png', null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='email',
            field=models.CharField(max_length=200, null=b'I01\n'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='telephone',
            field=models.CharField(max_length=200, null=b'I01\n'),
        ),
    ]
