# Generated by Django 4.0.4 on 2022-05-22 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_alter_authuser_user_type_alter_reviewer_contact_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authuser',
            name='user_type',
            field=models.PositiveSmallIntegerField(choices=[(2, 'Customer'), (4, 'Reviewer'), (3, 'Customer Manager'), (1, 'Product Manager')], null=True),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='isarchived',
            field=models.BooleanField(null=b'I01\n'),
        ),
    ]
