# Generated by Django 4.0.4 on 2022-05-22 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_alter_authuser_user_type_alter_product_isarchived_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authuser',
            name='user_type',
            field=models.PositiveSmallIntegerField(choices=[(2, 'Customer'), (3, 'Customer Manager'), (1, 'Product Manager'), (4, 'Reviewer')], null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='rating',
            field=models.FloatField(default=True),
        ),
    ]
