# Generated by Django 4.0.4 on 2022-05-22 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_alter_authuser_user_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authuser',
            name='user_type',
            field=models.PositiveSmallIntegerField(choices=[(3, 'Customer Manager'), (1, 'Product Manager'), (2, 'Customer'), (4, 'Reviewer')], null=True),
        ),
    ]
