# Generated by Django 4.0.4 on 2022-05-22 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0011_alter_authuser_user_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supplierproduct',
            name='supplier',
        ),
        migrations.AlterField(
            model_name='authuser',
            name='user_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Product Manager'), (4, 'Reviewer'), (3, 'Customer Manager'), (2, 'Customer')], null=True),
        ),
    ]
