# Generated by Django 4.0.4 on 2022-05-22 11:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0012_remove_supplierproduct_supplier_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplierproduct',
            name='supplier',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.supplier'),
        ),
        migrations.AlterField(
            model_name='authuser',
            name='user_type',
            field=models.PositiveSmallIntegerField(choices=[(4, 'Reviewer'), (2, 'Customer'), (1, 'Product Manager'), (3, 'Customer Manager')], null=True),
        ),
    ]
