# Generated by Django 4.0.4 on 2022-05-22 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0013_supplierproduct_supplier_alter_authuser_user_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='isFeatured',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='authuser',
            name='user_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Product Manager'), (2, 'Customer'), (3, 'Customer Manager'), (4, 'Reviewer')], null=True),
        ),
    ]
