# Generated by Django 4.0.4 on 2022-05-22 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0014_product_isfeatured_alter_authuser_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmanager',
            name='profilepicture',
            field=models.ImageField(blank=True, default='/assets/default_pfp.png', null=True, upload_to=''),
        ),
    ]
