# Generated by Django 4.0.4 on 2022-05-22 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0015_alter_productmanager_profilepicture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authuser',
            name='user_type',
            field=models.PositiveSmallIntegerField(choices=[(3, 'Customer Manager'), (2, 'Customer'), (4, 'Reviewer'), (1, 'Product Manager')], null=True),
        ),
        migrations.AlterField(
            model_name='productmanager',
            name='profilepicture',
            field=models.ImageField(blank=True, default='default_pfp.png', null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='reviewer',
            name='profilepicture',
            field=models.ImageField(blank=True, default='default_pfp.png', null=True, upload_to=''),
        ),
    ]
