# Generated by Django 4.0.4 on 2022-05-23 07:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0020_alter_authuser_user_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productphotos',
            name='filename',
        ),
        migrations.RemoveField(
            model_name='productvideos',
            name='filename',
        ),
        migrations.AlterField(
            model_name='authuser',
            name='user_type',
            field=models.PositiveSmallIntegerField(choices=[(2, 'Customer'), (3, 'Customer Manager'), (1, 'Product Manager'), (4, 'Reviewer')], null=True),
        ),
        migrations.AlterField(
            model_name='productphotos',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.product'),
        ),
        migrations.AlterField(
            model_name='productvideos',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.product'),
        ),
    ]
