# Generated by Django 4.0.4 on 2022-05-23 07:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0021_remove_productphotos_filename_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authuser',
            name='user_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Product Manager'), (2, 'Customer'), (3, 'Customer Manager'), (4, 'Reviewer')], null=True),
        ),
        migrations.AlterField(
            model_name='productphotos',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='catalog.product'),
        ),
        migrations.AlterField(
            model_name='productvideos',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='catalog.product'),
        ),
    ]
