# Generated by Django 4.0.4 on 2022-05-23 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0022_alter_authuser_user_type_alter_productphotos_product_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='profilepicture',
            field=models.ImageField(blank=True, default='/default_pfp.png', null=True, upload_to='suppliers'),
        ),
        migrations.AlterField(
            model_name='authuser',
            name='user_type',
            field=models.PositiveSmallIntegerField(choices=[(2, 'Customer'), (3, 'Customer Manager'), (4, 'Reviewer'), (1, 'Product Manager')], null=True),
        ),
    ]
