# Generated by Django 4.0.4 on 2022-05-23 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0024_rename_profilepicture_supplier_displaypicture_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authuser',
            name='user_type',
            field=models.PositiveSmallIntegerField(choices=[(2, 'Customer'), (3, 'Customer Manager'), (4, 'Reviewer'), (1, 'Product Manager')], null=True),
        ),
    ]
